[Feature] Better multi-line support for prompt elements
fadeevab/cliclack pull request #26
Opened 2024-03-28 08:35 UTC by cylewitruk

Here's an example implementation for #20 (spinner only).

@fadeevab thoughts?

2024-03-28 15:49 UTC, fadeevab requested changes

2024-03-28 15:49 UTC, fadeevab commented on src/theme.rs
> +        // )
Remove
```suggestion
```

2024-03-28 15:49 UTC, fadeevab commented on src/theme.rs
> +            };
Instead of copy-pasting the whole `format!` twice, you can define `{bar}  {line}{end}`, where `end` is either empty "", or "\n{S_BAR_END}".

2024-03-28 15:50 UTC, fadeevab commented
I like that this PR is backward compatible from perspective to user experience: the one-line spinner stays the same as the original.

2024-03-28 18:07 UTC, cylewitruk commented
> I like that this PR is backward compatible from the perspective of user experience: the one-line spinner stays the same as the original.

Are you open for expanding this to the rest of the prompt elements in that case?

> I like that this PR is backward compatible from the perspective of user experience: the one-line spinner stays the same as the original.

Are you OK with this being applied to all other prompt elements as well?

2024-03-28 18:50 UTC, fadeevab commented
> > I like that this PR is backward compatible from the perspective of user experience: the one-line spinner stays the same as the original.
> 
> Are you open to expanding this to the rest of the prompt elements in that case?

For the prompt hints (headers)? Perhaps, why not, if the patch will be simple.

2024-03-30 12:14 UTC, cylewitruk commented
> For the prompt hints (headers)? Perhaps, why not, if the patch will be simple.

@fadeevab pushed with support for all prompts now. I haven't thoroughly tested yet so don't merge, but have a look at the impl and let me know if it looks okay :pray:

2024-03-30 13:47 UTC, fadeevab commented
@cylewitruk yeah, it works, I probably can submit right into your PR

2024-03-30 14:26 UTC, fadeevab commented
@cylewitruk I pushed into your PR.
![image](https://github.com/fadeevab/cliclack/assets/5967447/946ef04e-8e91-414b-a186-ad8df62b5e67)

Takes interaction into account:
![image](https://github.com/fadeevab/cliclack/assets/5967447/c4d9783a-4b68-4e7e-8104-516cc236a55c)

Thoughts about spinner's style?

2024-03-30 15:07 UTC, fadeevab commented
@cylewitruk Basically, I'm ready to merge.

2024-03-30 15:13 UTC, cylewitruk commented
> @cylewitruk Basically, I'm ready to merge.

Nice! My only thought would be if the last mutiline should be on an S_BAR_END or if it should be contained _within_ the block?

2024-03-30 15:17 UTC, fadeevab commented
`S_BAR_END` outlines the end of the whole prompt block, so I can't break it in the middle, because then it looks like 2 prompts

2024-03-30 15:18 UTC, fadeevab approved these changes

2024-03-30 15:23 UTC, merged

2024-03-30 17:47 UTC, cylewitruk commented
> `S_BAR_END` outlines the end of the whole prompt block, so I can't break it in the middle, because then it looks like 2 prompts

Ah I meant more if it should be:

```
◇ Line 1
│ Line 2
│ 
│ Hello
└

Vs.

...
│
└ Hello
```

2024-03-30 19:14 UTC, fadeevab commented
@cylewitruk I was thinking: if you need the option 2, you can add `\n` in the end. So the current version is more agile. Also, as for me, the option 2 looks like there is an input in the middle.

2024-03-31 06:07 UTC, cylewitruk commented
> @cylewitruk I was thinking: if you need the option 2, you can add `\n` in the end. So the current version is more agile.

Good point, didn't think of that! 😁