Add support for Ctrl-C handling
fadeevab/cliclack pull request #8
Opened 2024-01-11 19:26 UTC by samuela

Fix https://github.com/fadeevab/cliclack/issues/7.

I was hoping that there would be a way to accomplish this without requiring any changes from user code, but I have not yet found a solution to https://github.com/Detegr/rust-ctrlc/issues/106#issuecomment-1887793468.

In any case, this PR fixes the issue such that Ctrl-C is now handled the same as Esc, assuming client code sets up a signal handler. Crucially it does not steal the user's cursor anymore.

2024-01-12 00:48 UTC, fadeevab commented
@samuela Hey, thanks for the PR and for feature requests, I have just noticed them. I'll check it a bit later today or tomorrow!

2024-01-12 14:01 UTC, fadeevab requested changes
This is cool, I also experimented with `ctrlc` crate once trying to make `Ctrl-C` work I just didn't realize the empty handler is enough.

2024-01-12 14:01 UTC, fadeevab commented on examples/basic.rs
> +
```suggestion
    // Set a no-op Ctrl-C handler so that Ctrl-C results in
    // `Esc` behavior because of a `term.read_key()` error
    // instead of terminating the process. You can skip
    // this step if you have your own Ctrl-C handler already set up.
    //
    // We cannot (easily) handle this at the library level due to
    // https://github.com/Detegr/rust-ctrlc/issues/106#issuecomment-1887793468.
    ctrlc::set_handler(move || {}).expect("setting Ctrl-C handler");

```

2024-01-12 14:01 UTC, fadeevab commented on examples/basic_dynamic_items.rs
> +    ctrlc::set_handler(move || {}).expect("Error setting Ctrl-C handler");
I would suggest simplifying the comment in all other examples except the basic one. You can choose your wording. :) I would also prefer `expect` with the non-capitalized first letter like a plain sentence "expect setting blah blah" (I recently found this Rust code style advice and it looks cool when it panics).
```suggestion
    // Set a no-op Ctrl-C to make it behave as `Esc` (see the basic example).
    ctrlc::set_handler(move || {}).expect("setting Ctrl-C handler");
```

2024-01-12 14:01 UTC, fadeevab commented on examples/theme.rs
> +    ctrlc::set_handler(move || {}).expect("Error setting Ctrl-C handler");
```suggestion
     // Set a no-op Ctrl-C to make it behave as `Esc` (see the basic example).
    ctrlc::set_handler(move || {}).expect("setting Ctrl-C handler");
```

2024-01-14 11:46 UTC, fadeevab commented
@samuela Alternatively, I can merge this PR and correct it with my additional commit.

2024-01-14 22:39 UTC, samuela commented
Hi @fadeevab , thanks for your review! Just applied the suggestions in https://github.com/fadeevab/cliclack/pull/8/commits/3b5104bc7e31d57a7c278d6e6857fbc53bcee185!

2024-01-17 00:25 UTC, fadeevab approved these changes

2024-01-17 00:25 UTC, merged

2024-01-17 00:26 UTC, fadeevab commented
@samuela merged, thanks 👍