Added accounting for terminal size
fadeevab/cliclack pull request #83
Opened 2024-10-28 12:46 UTC by BjornTheProgrammer

Fixes #62 and #79, and is based upon work in #73, but just refined.

Adds one external API called `set_size` to modify the number of rows displayed at once for `select` and `multiselect`.

By default, this ensures that there are not more than the maximum possible rows displayed at once.

2024-10-31 17:11 UTC, fadeevab commented
@BjornTheProgrammer Thanks! I'll check it out later. As of now, apply `rustfmt` over your changes (Alt+Shift+F in vscode), I can see TABs and some formatting inconsistencies.

2024-11-01 04:13 UTC, BjornTheProgrammer commented
Whoops, should be fixed now. I ran `cargo fmt`, which should be the same as VSCode's.

2024-11-09 00:24 UTC, BjornTheProgrammer commented
I realized that the test used the wrong function name, I've updated that.

2025-01-07 17:31 UTC, BjornTheProgrammer commented
Makes perfect sense! I'll implement the change as requested. Probably should have done this to begin with 😅️.

2025-01-07 17:58 UTC, BjornTheProgrammer commented
Should be implemented now, please let me know if you have any other issues!

2025-01-07 17:58 UTC, furbyhaxx commented
termsize does not work for SSH terminals, like RustRover trough Jetbrains Gateway.
I made a fix will submit a PR for termsize which fixes this, but until then we could directly integrate a workaround for this case:

```rust
extern crate libc;

use std::io::IsTerminal;

use std::ffi::{c_ushort, CString};

use self::{
    super::Size,
    libc::{ioctl, O_RDONLY, STDOUT_FILENO, TIOCGWINSZ},
};

/// A representation of the size of the current terminal
#[repr(C)]
#[derive(Debug)]
pub struct UnixSize {
    /// number of rows
    pub rows: c_ushort,
    /// number of columns
    pub cols: c_ushort,
    x: c_ushort,
    y: c_ushort,
}


/// Workaround for SSH terminal size
pub fn get_term_size() -> Option<termsize::Size> {
    if cfg!(target_os = "windows") {
        termsize::get()
    } else {
        _get_unix_termsize()
    }
}

/// Gets the current terminal size
fn _get_unix_termsize() -> Option<termsize::Size> {
    // http://rosettacode.org/wiki/Terminal_control/Dimensions#Library:_BSD_libc
    if !std::io::stdout().is_terminal() {
        return None;
    }
    let mut us = UnixSize {
        rows: 0,
        cols: 0,
        x: 0,
        y: 0,
    };

    let fd = if let Ok(ssh_term) = std::env::var("SSH_TTY") {
        // Convert path to a C-compatible string
        let c_path = CString::new(ssh_term).expect("Failed to convert path to CString");

        // Open the terminal device
        let fd = unsafe { libc::open(c_path.as_ptr(), O_RDONLY) };
        if fd < 0 {
            return None; // Failed to open the terminal device
        }

        fd
    } else {
        STDOUT_FILENO
    };

    let r = unsafe { ioctl(fd, TIOCGWINSZ, &mut us) };

    if r == 0 {
        Some(termsize::Size {
            rows: us.rows,
            cols: us.cols,
        })
    } else {
        None
    }
}
```

Here we can just call get_term_size instead of termsize::get() but it introduces a new dependency (libc).

2025-01-08 06:04 UTC, BjornTheProgrammer commented
I'm more than willing to add libc as a temporary fix, but it really is  up to whether @fadeevab wants it. If you want to use this patch now, without waiting for your termsize patch to be merged, you could probably override both dependencies in the cargo.toml

2025-01-08 18:07 UTC, fadeevab commented
Hey, folk! You're still here 😄
If you want to bring a `libc` dependency, do it in a cross-platform way: the code should compile on Windows.

Other than that, I think the "size" in the PR always actually means "height", or "rows", or "max_height". Like, "term_max_height" or "frame_height"/"frame_max_height".

Overall, I think the "max height" should always be detected automatically. If you want to expose the `set_height` (`set_max_height`?) method, you must test corner cases: What if I resize the terminal to the height of two rows?

2025-01-08 19:01 UTC, BjornTheProgrammer commented
>  If you want to bring a libc dependency, do it in a cross-platform way: the code should compile on Windows.

Yup, it could be a target libc with something like
```rust
[target.'cfg(unix)'.dependencies]
libc = "0.2"
```

> Other than that, I think the "size" in the PR always actually means "height", or "rows", or "max_height". Like, "term_max_height" or "frame_height"/"frame_max_height".

Totally agree here, I think the best name would be rows though. Since (at least in unix) that is how it is treated.

> Overall, I think the "max height" should always be detected automatically. If you want to expose the set_height (set_max_height?) method, you must test corner cases: What if I resize the terminal to the height of two rows?

I'll do some more testing, but thanks to @furbyhaxx the smaller than 3 corner cases should be handled.

> Overall, I think the "max height" should always be detected automatically. If you want to expose the set_height (set_max_height?) method, you must test corner cases: What if I resize the terminal to the height of two rows?

I believe this is already the case? The default function detects the number of rows, and sets the max height to that by default.

2025-01-08 19:16 UTC, furbyhaxx commented
We should also verify that your -3 margin is always a sane default.

I needed to change it to 5 to get a select with filter completely fit the terminal. But could be because of the type of terminal I use currently.

2025-01-08 19:28 UTC, BjornTheProgrammer commented
Yeah, the 3 was there since that is just for the "Select an Item", the search, and the final empty closing line. Probably should at the very least include one or two items.

Other than that I just made a commit, which compiles for unix and windows, which should theoretically fix the ssh issue. Mind giving it a try? Anyone who has a windows computer should probably test the new commit as well.

2025-01-13 16:27 UTC, fadeevab commented
Hi guys, a busy week, I remember about the PR, I'll try to get back to it "ASAP"

2025-01-25 21:07 UTC, fadeevab requested changes
@BjornTheProgrammer We're gonna simplify and minimize your patch! :) See review comments. Thank you for your contribution!

2025-01-25 21:07 UTC, fadeevab commented on src/multiselect.rs
> +            .set_max_rows(term_size.checked_sub(1).unwrap_or(term_size));
This trick is not gonna work if you set `filter_mode` _before_ setting the "max rows". Usually, these setters should be more or less pure/idempotent.

You should remove it here and check the "filter_mode" somewhere, perhaps, in the `on` callback incrementing or decrementing "1" as needed.

2025-01-25 21:07 UTC, fadeevab commented on src/prompt/term.rs
> +    window_pos: usize,
Let's just remove the `window_` prefix :)

2025-01-25 21:07 UTC, fadeevab commented on src/prompt/term.rs
> +pub(crate) struct TermSize {
The better naming would be `Frame`. The module is managing a fixed-size "frame" within which content is displayed and scrolled, similar to a window frame.

2025-01-25 21:07 UTC, fadeevab commented on src/prompt/term.rs
> +    pub fn get_pos(&self) -> usize {
`pos` -> `offset`

2025-01-25 21:07 UTC, fadeevab commented on src/select.rs
> +            .take(self.term.get_max_rows())
After renaming it's gonna be like

```
.skip(self.frame.get_offset())
.take(self.frame.get_max_rows())

2025-01-25 21:07 UTC, fadeevab commented on src/prompt/term.rs
> +        }
I realized that it just not needed. Try to shrink your terminal to a few rows of height, and then run the `cargo run --example filter`:  the list is gonna be forever of a few rows, even if you expand the terminal height.

So, with `max_rows = usize::MAX` by default, the lists are gonna be working in an old way, which is good for backward compatibility.

2025-04-05 21:31 UTC, closed without merging

2025-04-05 21:31 UTC, fadeevab commented
Closed in favor of PR #91

2025-04-05 21:35 UTC, fadeevab commented
Selection lists now have a scrolling behavior after setting a `max_rows` number. Thanks @BjornTheProgrammer for providing this PR, which is mainly used for the implementation, I just polished it and refactored.